import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <script src="https://accounts.google.com/gsi/client" async defer></script>
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
