import Header from "./components/header";
import Menu from "./components/menu";
import Search from "./components/search";
import { DrawerWrapper } from "./components/drawerWrapper";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen flex flex-col">
          <header>
            <Header />
          </header>
          <main className="flex flex-1 overflow-hidden">
            <Menu />
            <div className="w-full h-full flex flex-col relative overflow-y-auto bg-gradient-to-br from-gray-50/50 to-white">
              <DrawerWrapper />
              <div className="sticky top-0 z-30 bg-white/80 backdrop-blur-sm border-b border-gray-200/50 px-5 pt-4 pb-2">
                <Search />
              </div>
              <div className="flex-1 p-5 pt-4">{children}</div>
            </div>
          </main>
          <footer></footer>
        </div>
      </body>
    </html>
  );
}
